### PR TITLE
Regression test a load of scenarios

### PR DESCRIPTION
**Pull request by NickGrantX**
# Motivation and Context
The ATs are taking 18+ minutes to run in CI... far too long.

# What has changed
Moved a load of scenarios into regression testing.

# How to test?
Run the ATs.

# Links
Trello: https://trello.com/c/YeIPO3TC

### CODE REVIEW

**Comment by NickGrantX** [comment]
[ATs are taking an eternity in CI pipeline](https://trello.com/c/YeIPO3TC/1264-ats-are-taking-an-eternity-in-ci-pipeline)

**Review by LukeLoze1 — COMMENTED** [review]
Last time I moved rows from this table into regression there was controversy about breaking the order of the table.

**Comment by NickGrantX** [comment]
> Last time I moved rows from this table into regression there was controversy about breaking the order of the table.

Boo hoo

**Review by AdamHawtin — APPROVED** [review]
> Last time I moved rows from this table into regression there was controversy about breaking the order of the table.

That was probably me, the table has grown a lot since then and this change looks to still be testing all the different behaviours, so I'm ok with it.

**Review by LukeLoze1 — APPROVED** [review]

**Pull request merged**
