### PR TITLE
changes tests to look for <filename>.csv.gpg files

### PR DESCRIPTION
**Pull request by davidmort**
# Motivation and Context
changes have been made to the print-file-service to add ".gpg" extensions to encrypted files

# What has changed
updated tests to look for *.csv.gpg filenames

# How to test?
run these acceptance tests against this [print-file-service](https://github.com/ONSdigital/census-rm-acceptance-tests/tree/append-gpg-to-print-file-extension) branch and they should pass

### CODE REVIEW

**Comment by davidmort** [comment]
[Append '.gpg' to encrypted print files (3)](https://trello.com/c/6RM6YjmE/965-append-gpg-to-encrypted-print-files-3)

**Review by NickGrantX — CHANGES_REQUESTED** [review]
You will need to modify line 101.

Change `replace(".csv"` to be `replace(".csv.gpg`.

**Comment by jcox-dev** [comment]
@NickGrantONS strange how the tests pass regardless 🤔

**Comment by davidmort** [comment]
@NickGrantONS i don't think we need to change that line as manifest files don't need the .gpg extension, its just for the encrypted files.

**Review by liamtoozer — COMMENTED** [review]
I think [this line](https://github.com/ONSdigital/census-rm-acceptance-tests/blob/002997e07d0fa0face8f2255eb9651a6bf93b7c9/acceptance_tests/features/steps/print_file_steps.py#L81) will also need to be updated so it checks the related manifest file?

**Comment by davidmort** [comment]
@liamtoozer i don't think so as the manifest files haven't changed, only the encrypted files need the .gpg file extension

**Comment by davidmort** [comment]
@NickGrantONS @liamtoozer ah actually you might be right, ill take another look 👍 , it is strange that the tests still pass tho 🤔

**Review by NickGrantX — CHANGES_REQUESTED** [review]
I think line 81 needs to change too.

`if _file.filename.endswith(".csv"):` should be `if _file.filename.endswith(".csv.gpg"):`

**Comment by davidmort** [comment]
@NickGrantONS @liamtoozer added those changes. will raise a ticket to improve the test around finding manifests, basically at the moment if it doesn't match any print files then that function just exits and carries on regardless.....

**Review by NickGrantX — APPROVED** [review]
LGTM 👍

**Review by liamtoozer — APPROVED** [review]
LGTM 👍

**Pull request merged**
