### PR TITLE
passes flag to sample_loader to return sample_units, ups version of s…

### PR DESCRIPTION
**Pull request by LukeLoze1**
# Motivation and Context
load_sample_file now has option to store and return the loaded sample units

# What has changed
Upped version of sample_loader to v1.0.1, added flag to load_sample_file

# How to test?
With the sample_loader from this ticket
You will have to change the the pipfile in the ATs to 
census-rm-sample-loader = {editable = true,git = "https://github.com/ONSdigital/census-rm-sample-loader", ref = "load-sample-flag-to-return-sample-units”} 

Run the tests and they should continue to work

# Links
https://trello.com/c/luQsADkR/640-enhance-sampleloader-script-8

### CODE REVIEW

**Review by ryangrundy7 — COMMENTED** [review]
Don't think you need the src directory

**Review by NickGrantX — CHANGES_REQUESTED** [review]
You got what looks like a bona fide build error

**Comment by LukeLoze1** [comment]
> You got what looks like a bona fide build error

yeah it's because sample_loader must be released first, then this built locally and pushed.

**Review by ryangrundy7 — APPROVED** [review]

**Review by NickGrantX — APPROVED** [review]
LGTM 👍

**Pull request merged**
