### PR TITLE
update test to check for formtype and questionnairetype

### PR DESCRIPTION
**Pull request by hbrace**
# Motivation and Context

we need to return formType and questionnaire type in the the qid telephone capture endpoints on the case-api
# What has changed

Telephone capture test updated to check for correct formtype and quesitonnairetype.
# How to test?

Run with case-api built on branch of the [same name](https://github.com/ONSdigital/census-rm-case-api/pull/61).
# Links

https://trello.com/c/kCViPjQB/523-add-formtype-and-questionnaire-type-to-case-api-5
# Screenshots (if appropriate):

### CODE REVIEW

**Comment by hbrace** [comment]
[add formtype and questionnaire type to case api (5)](https://trello.com/c/kCViPjQB/523-add-formtype-and-questionnaire-type-to-case-api-5)

**Review by ryangrundy7 — APPROVED** [review]
ATs pass

**Comment by LeoKHoward** [comment]
The case-api build passed but all of the telephone capture ATs failed for me. Not sure if that is just my local environment playing up though so someone else should check these out. 

Same error for each failure: 

KeyError: 'formType'

**Review by NickGrantX — APPROVED** [review]
Nice. Very neat. Good work 👍

**Pull request merged**
