### PR TITLE
Fix tests broken by FWMT XML to JSON conversion

### PR DESCRIPTION
**Pull request by NickGrantX**
# Motivation and Context
Fieldwork were still using legacy XML messages to receive instructions from RM. We wanted to modernise and use JSON.

# What has changed
Migrated from XML to JSON

# How to test?
Run the acceptance tests.

# Links
Trello: https://trello.com/c/VsrzpkgG/492-xml-to-json-for-field-messages-create-and-close-13

### CODE REVIEW

**Comment by NickGrantX** [comment]
[XML to JSON for field messages - Create and Close (13)](https://trello.com/c/VsrzpkgG/492-xml-to-json-for-field-messages-create-and-close-13)

**Review by ryangrundy7 — CHANGES_REQUESTED** [review]
getting errors in the undelivered.feature on this line`an ActionRequest event is sent to field work management`. Error is `Assertion Failed: True != 'true'`

**Review by liamtoozer — APPROVED** [review]
LGTM 👍 Tests passing locally

**Review by davidmort — DISMISSED** [review]
Im afraid we need to block this atm as we're not sure if the FWMT team are ready for these changes :(

**Review by ryangrundy7 — APPROVED** [review]
Looks good! couple tests failed but guessing it because master hasn't been merged

**Pull request merged**
