### PR TITLE
decrypting sftp files

### PR DESCRIPTION
**Pull request by ryangrundy7**
# Motivation and Context
We've had to alter the acceptance tests code to decrypt files when they're coming in from the sftp. 

# What has changed
- decrypt files from sftp
- Altered manifest to match strict specifications

# How to test?
Run the acceptance tests. Use action scheduler branch `new-json-printer-msg` and docker-dev branch Removing-action-exporter and print-file-service branch `add-distribution-functionality`

# Links
[Trello](https://trello.com/c/xgyARfxB)

### CODE REVIEW

**Comment by ryangrundy7** [comment]
[Add acceptance test for print file service (3)](https://trello.com/c/XDc82Fzs/908-add-acceptance-test-for-print-file-service-3)

**Review by gavinleeedwards — APPROVED** [review]
All tests pass against the required branches 👍

**Review by hbrace — APPROVED** [review]

**Review by NickGrantX — APPROVED** [review]
ATs passing. Works for me. Looks good 👍

**Review by AdamHawtin — APPROVED** [review]
👍 Passed locally and in k8s against a local SFTP 🎉

**Pull request merged**
