### PR TITLE
Use SSH login to SFTP instead of username & password

### PR DESCRIPTION
**Pull request by NickGrantX**
# Motivation and Context
Currently we log into our SFTP server using a username and password. This is heresy. We should use SSH pub/private key pair to login, because this is what the GoNowhere FTP server will use.

# What has changed
Remove 'password' references. Add private key (dummy). Add private key & passphrase config. Configure SFTP to connect using SSH.

# How to test?
Run the acceptance tests along with `census-rm-action-exporter` and `census-rm-docker-dev` from the branch `sftp-ssh-login`.

# Links
Trello: https://trello.com/c/Exdafhu8

### CODE REVIEW

**Comment by NickGrantX** [comment]
[SPIKE: Use SSH login to SFTP instead of username & password (4 hours)](https://trello.com/c/Exdafhu8/797-spike-use-ssh-login-to-sftp-instead-of-username-password-4-hours)

**Review by hbrace — APPROVED** [review]

**Review by LukeLoze1 — APPROVED** [review]

**Comment by NickGrantX** [comment]
[RMC-179 Implement new print file distribution method 'GoAnywhere' (8)](https://trello.com/c/B6lVt679/611-rmc-179-implement-new-print-file-distribution-method-goanywhere-8)

**Review by jcox-dev — DISMISSED** [review]
[Pipeline task](https://github.com/ONSdigital/census-rm-acceptance-tests/blob/master/tasks/kubectl-run-acceptance-tests.yml) will need updating for this to work in Concourse / k8s.

```bash
--env=SFTP_KEY_FILENAME...
--env=SFTP_PASSPHRASE...
```

**Comment by NickGrantX** [comment]
[RMC-179 Implement new print file distribution method 'GoAnywhere' (8)](https://trello.com/c/B6lVt679/611-rmc-179-implement-new-print-file-distribution-method-goanywhere-8)

**Pull request merged**
